# Generated by Django 4.1.7 on 2023-03-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_type_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Stored', 'Stored'), ('Transit', 'Transit'), ('Returned', 'Returned'), ('Damaged', 'Damaged'), ('Sold', 'Sold')], default='Unset', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='no warranty', max_length=60),
        ),
    ]
